
#define VIM_DO_ANIMATE                 1
#define VIM_USE_TRADITIONAL_CHORDS     0
#define VIM_USE_REIGSTER_BUFFER        1

enum MAXLISUI_Vim_Request{
	MAXLISUI_REQUEST_Title,
	MAXLISUI_REQUEST_Comment,
	MAXLISUI_REQUEST_UnComment,

	MAXLISUI_REQUEST_COUNT
};

enum MAXLISUI_Vim_Objects{
	MAXLISUI_OBJECT_param0,
	MAXLISUI_OBJECT_param1,
	MAXLISUI_OBJECT_camel0,
	MAXLISUI_OBJECT_camel1,

	MAXLISUI_OBJECT_COUNT
};
#define VIM_ADDITIONAL_REQUESTS        MAXLISUI_REQUEST_COUNT
#define VIM_ADDITIONAL_TEXT_OBJECTS    MAXLISUI_OBJECT_COUNT

#define VIM_ADDITIONAL_PEEK            2

#define VIM_DEFAULT_REGISTER           unnamed

#define VIM_USE_BOTTOM_LISTER          1
#define VIM_LISTER_RANGE               3,5
#define VIM_LISTER_MAX_RATIO           0.55f
